- name: Create an ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    #key_name:  #  Need to Change
    aws_access_key: ""  #  Need to Change
    aws_secret_key: ""  #  Need to Change
   # group: launch-wizard-2  # security group name
    group: SG1  # security group name
    instance_type: "{{ instance_type}}"
    image: "{{ ami }}"  
    wait: true
    #region: " {{ region }} "  
    region: "us-east-2"
    count: 1  # default
    count_tag:
      Name: "Demo"
    instance_tags:
      Name: "Demo"
    vpc_subnet_id: "subnet-b96cf1c3"  #  Need to Change
    assign_public_ip: yes
  register: ec2
    
- debug:
    msg: "{{ item['private_ip'] }}"
  with_items: "{{ ec2.instances }}"

- name: Add all web instance IPs to host group
  add_host: 
    hostname: "{{ item.private_ip }}"
    groupname: webservers
    ansible_user: ec2-user 
  with_items: '{{ ec2.instances }}'

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: '{{ ec2.instances }}'
       

